project:
  type: book
  output-dir: docs
  

book:
  title: "locks5notes"
  author: "math4mads"
  date: "9/30/2023"
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: ch1:Collecting data
      chapters: 
        - ./books/ch01/ch1.1.qmd
        - ./books/ch01/ch1.1-exe.qmd
        - ./books/ch01/ch1.2.qmd
        - ./books/ch01/ch1.3.qmd
    - part: ch2:Describing Data
      chapters: 
        - ./books/ch02/ch02.qmd
        - ./books/ch02/ch02.1.qmd
   
  
number-depth: 1 
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true

  



