---
title: "ch1.1-exercises"
author: math4mad
bibliography: ch01.bib
---

:::{.callout-note title="skillbuild"}
   ch1.1  练习
:::

## load package
```{julia}
using Distributions, Random,Pipe
include("../utils.jl")  # import load_csv function 
Random.seed!(3434)
```

## 1. skill building-1

1.1-1.6 要求每行记录是什么含义, 变量是定量还是分类变量

>  可以在理解的基础上试着生成问题的模拟数据

- 1.1 调查城市里居民是否支持环保法案
  
这里有两种态度, 要么支持, 要么反对, 可以用伯努利分布来模拟
伯努利分布通常的例子是硬币试验, 城市里居民对法案的支持程度一样,可以用一个参数
表示 假设$\theta$



```{julia}
dist=Bernoulli(0.6)
data1=rand(dist, 100)

# 1 表示支持, 0 表示反对
"城市居民对环保法案的态度"=>data1

```

- 1.2  100种股票的百分比变化

- 1.3  对一组青少年进行调查, 内容为每天摄食水果和蔬菜的次数是否大于 5 次
```{julia}
dist2=Bernoulli(0.4)
data2=rand(dist, 100)

# 1 表示5 次以上, 0 表示没有达到 5 次
"摄食水果和蔬菜的次数是否大于 5 次"=>data2
```

-  1.4 测量陈列柜里香蕉直到腐烂变质的天数
  
用泊松分布来模拟这个数据,假定平均腐烂变质的时间为 5天
```{julia}
dist3=Poisson(5)
rand(dist3,20)
```

-  1.5 估计横梁抗弯曲力

可以用正态分布来模拟这个数据, 假定最大抗弯曲里为 100N,标准差为 5
```{julia}
dist5=Normal(100,5)
rand(dist5,10)
```

- 1.6 记录全世界国家里识字率是否超过 75%
  以互联网人口比例代替识字率, 统计属性不同, 方法相同
  ```{julia}
   allcountry_data=Lock5Table(28,"AllCountries","Literacy>75%",[:Internet])
   df=@pipe load_csv(allcountry_data.name)|>select(_,allcountry_data.feature)|>Matrix|>vec
   map(x->x>75 ? 1 : 0,df)
  ```

  ## 2. skill building 2

  1.7-1.10 探索两个变量之间的关系, 可以认为一个变量帮助我们理解和解释另一个变量

  >- 1.7  肺活量与吸烟年限的关系
   
    通常认识吸烟会损伤肺部组织,所以随着吸烟时间的加长,肺活量会变小. 但是这里要
    注意, 随着年龄增长, 肺部功能自然会消退, 所以影响肺活量大小的不止一个因素.

  >- 1.8  施肥量与农作物收成的关系

    在阈值之内, 施肥量增加,作物收成会增加, 超过阈值时,对作物有害,会降低收成

  > - 1.9  血液内酒精浓度(BAC)和饮酒量之间的关系
    
    随着饮酒量增加, BAC 浓度会增加. 存在因果关系

  > - 1.10 年份与马拉松成绩

    随着时间靠近现代, 马拉松成绩越来愈好, 但是这不是因果关系, 引起成绩变好的原因是:
    训练水平的提高,和训练方法的改进

  - 1.11  
    
  - 1.13 童话故事效应

    参见  @Hutton2018DifferencesIF , 通过研究27 个 4 岁大的孩子三种阅读环境下脑部 MRI 活动情况提出观点:
    与音频资料和动画相比, 童话故事对刺激脑部活性
    的能力最大化, 因此对儿童脑部发育比其他两种方法好

    解释变量为分类变量表示不同的阅读方法
    响应变量是脑部连接的活性
    共有 27 个实验研究对象

  - 1.14 女性游戏玩家是否受到性骚扰?
    
    在英国, 咨询公司问询了 1151 个女性游戏玩家, 结果 40%玩家在游戏过程中收到过淫秽消息,
    调查的属性还包括每周的游戏时间,以及游戏角色是否有鲜明的女性特征

  - 1.15  主动学习与被动学习,哪个更为有效?
  
    参见 @Deslauriers2019MeasuringAL

    主动学习(Active Learning):学生更多的参与教学活动中(单个或者小组形式)
    被动学习(Passive Learning):传统老师教授内容, 学生记笔记

  - 1.16 蜘蛛的性游戏
    
    蜘蛛通常会进行假的性行为,但是并没有真正进行交配. 

  - 1.17 激素与鱼的繁殖能力

    >妇女服用的避孕药还有雌激素,研究发现残留的药物最终会流入到湖泊中,在一项实验中
     研究者收集了若干湖泊的水样品, 测量了激素浓度(百万分之一浓度),并记录了鱼卵受精
     的百分比.

     >目的是研究水体中激素浓度是否对鱼的繁殖能力相关
      变量是激素浓度和卵受精比例

  - 1.18 Fast-Twitch Muscles and Race
    
    >ACTN3基因突变率在不同种族之间是否有差异?

    >参见 @North1999ACN

    >研究中发现 20%的高加索(白色人种), 25%亚洲人(黄色人种),1%非洲人(黑色人种)
    ACTN3基因有突变

  - 1.19
  - 1.20
  - 1.21  饮食的跨代效应
   
    > 父母的经历是否会影响到后代?
      喂食含脂肪率为43%(偏高)食物的大鼠后代比正常饮食大鼠的后代更容易患上代谢综合征
  - 1.27
  
    > 你的鼻子在变大吗?
      参见 @Sforza2011AgeAS
      研究者调查了 859 名参加实验者鼻子的大小, 表面积,高度和宽度,发现
      都有不同程度的增加, 同时还记录的参加实验者的性别, 发现男性鼻子各方面增加幅度
      大于女性

  
      
    





    


  